POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov">
    <soap:Body>
        <jets:getActorById>
            <arg0>1</arg0>
        </jets:getActorById>
    </soap:Body>
</soap:Envelope>