
POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllActors>
<!--            <arg0>1</arg0>-->
        </jets:AllActors>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:ActorById>
                        <actorId>1</actorId>
        </jets:ActorById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:searchByName>
            <actorName>CUBA</actorName>
        </jets:searchByName>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllActorFilms>
            <actorId>1</actorId>
        </jets:AllActorFilms>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:ActorFilmsByLanguage>
            <actorId>1</actorId>
            <language>English</language>
        </jets:ActorFilmsByLanguage>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:ActorFilmsByRating>
            <actorId>1</actorId>
            <rate>PG</rate>
        </jets:ActorFilmsByRating>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:NoOfFilms>
            <actorId>1</actorId>
        </jets:NoOfFilms>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:NoOfFilmsByLanguage>
            <actorId>1</actorId>
            <language>Italian</language>
        </jets:NoOfFilmsByLanguage>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:NoOfFilmsByRating>
            <actorId>1</actorId>
            <rate>PG</rate>
        </jets:NoOfFilmsByRating>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AddNewActor>
            <ActorObject>
                <firstName>Waffa</firstName>
                <lastName>Ammer</lastName>
            </ActorObject>
        </jets:AddNewActor>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:EditActor>
            <ActorId>207</ActorId>
            <ActorObject>
                <firstName>Ahmed</firstName>
                <lastName>Zaki2</lastName>
                <lastUpdate/>
            </ActorObject>
        </jets:EditActor>
    </soap:Body>
</soap:Envelope>