
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllCategories>
<!--            <arg0>1</arg0>-->
        </jets:AllCategories>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CategoryById>
                        <categoryId>1</categoryId>
        </jets:CategoryById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:searchByName>
            <categoryName>Hor</categoryName>
        </jets:searchByName>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
    <jets:CategoryFilms>
    <categoryId>5</categoryId>
    </jets:CategoryFilms>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:NoOfCategoryFilms>
            <categoryId>1</categoryId>
        </jets:NoOfCategoryFilms>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:NoOfCategoryFilms>
            <categoryId>1</categoryId>
        </jets:NoOfCategoryFilms>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:addCategory>
            <categoryName>Kids</categoryName>
        </jets:addCategory>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8070/apis/soap/category HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:editCategory>
            <categoryId>17</categoryId>
            <categoryName>Kides</categoryName>
        </jets:editCategory>
    </soap:Body>
</soap:Envelope>