
POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllCustomerList/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CustomerById>
            <customerId>601</customerId>
        </jets:CustomerById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllActiveCustomerList/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllInActiveCustomerList/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllCustomerCount/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllActiveCustomerCount/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllInActiveCustomerCount/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CustomerPaymentList>
            <customerId>1</customerId>
        </jets:CustomerPaymentList>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CustomerRentalList>
            <customerId>1</customerId>
        </jets:CustomerRentalList>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CustomerTotalPaymentAmount>
            <customerId>1</customerId>
        </jets:CustomerTotalPaymentAmount>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:CustomerRentalCount>
            <customerId>1</customerId>
        </jets:CustomerRentalCount>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:SearchCustomerByName>
            <customerName>DOLORES</customerName>
        </jets:SearchCustomerByName>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AddCustomer>
            <customer>
                <firstName>shaimaa</firstName>
                <lastName>Mohamed</lastName>
                <email>shosho@gmail.com</email>
                <active>true</active>
                <address>Cairo</address>
                <district>Shubra</district>
                <city>3</city>
                <country>101</country>
                <postalCode>45454</postalCode>
                <phone>010214541</phone>
                <store>4</store>
            </customer>
        </jets:AddCustomer>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/customer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:EditCustomer>
            <customerId>601</customerId>
            <customer>
                <firstName>Mohamed</firstName>
                <lastName>Mustafa</lastName>
                <email>mohamed222@gmail.com</email>
                <active>true</active>
                <address>LabLab2</address>
                <district>El-Salam</district>
                <city>3</city>
                <country>101</country>
                <postalCode>45454</postalCode>
                <phone>010214541</phone>
                <store>1</store>
            </customer>
        </jets:EditCustomer>
    </soap:Body>
</soap:Envelope>