POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:FilmText>
            <filmId>1018</filmId>
        </jets:FilmText>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllFilmText/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:FilmById>
            <filmId>1018</filmId>
        </jets:FilmById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllFilms/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:FilmInfoById>
            <filmId>1</filmId>
        </jets:FilmInfoById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:addFilm>
            <film>
                <title>ZORRO ARK S4</title>
                <description>A Intrepid Panorama of a Mad Scientist And a Boy who must Redeem a Boy in A Monastery</description>
                <releaseYear>2008</releaseYear>
                <rentalDuration>1</rentalDuration>
                <rentalRate>4.99</rentalRate>
                <length>50</length>
                <replacementCost>18.99</replacementCost>
                <rating>NC-17</rating>
                <specialFeatures>Trailers,Commentaries,Behind the Scenes</specialFeatures>
                <language>1</language>
                <category>5</category>
                <actor>1</actor>
                <store>1</store>
            </film>
        </jets:addFilm>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/film HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:DeleteFilm>
            <filmId>1019</filmId>
        </jets:DeleteFilm>
    </soap:Body>
</soap:Envelope>

