POST http://localhost:8070/apis/soap/payment HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:AllPayments/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/payment HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:PaymentById>
            <paymentId>1</paymentId>
        </jets:PaymentById>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8070/apis/soap/payment HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.soap.api.jets.iti.gov/">
    <soap:Body>
        <jets:count/>
    </soap:Body>
</soap:Envelope>